# Clúster Kafka de pagos — ESTADO FINAL DEL LAB 04 ("la puerta segura").
# Respecto al Lab 03:
#   - Se AÑADEN dos listeners externos de tipo nodeport (uno SCRAM, uno mTLS).
#   - Se ELIMINA el listener plano 9092 (la puerta vieja deja de existir).
# Quedan: tls(9093) y scram(9094) internos, externo-scram(9095) y
# externo-mtls(9096) externos, todos con authorization simple.
apiVersion: kafka.strimzi.io/v1
kind: Kafka
metadata:
  name: pagos
spec:
  kafka:
    version: 4.2.0
    metadataVersion: 4.2-IV1
    rack:
      topologyKey: topology.kubernetes.io/zone
    listeners:
      # --- Listeners internos (dentro del clúster) ---
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: tls
      - name: scram
        port: 9094
        type: internal
        tls: false
        authentication:
          type: scram-sha-512
      # --- Listener externo para APLICACIONES: TLS + SCRAM ---
      - name: extscram
        port: 9095
        type: nodeport
        tls: true
        authentication:
          type: scram-sha-512
        configuration:
          bootstrap:
            nodePort: 32000
          brokers:
            - broker: 0
              nodePort: 32001
              advertisedHost: 127.0.0.1
              advertisedPort: 32001
            - broker: 1
              nodePort: 32002
              advertisedHost: 127.0.0.1
              advertisedPort: 32002
            - broker: 2
              nodePort: 32003
              advertisedHost: 127.0.0.1
              advertisedPort: 32003
      # --- Listener externo para SERVICIOS CRÍTICOS: mTLS ---
      - name: extmtls
        port: 9096
        type: nodeport
        tls: true
        authentication:
          type: tls
        configuration:
          bootstrap:
            nodePort: 32004
          brokers:
            - broker: 0
              nodePort: 32005
              advertisedHost: 127.0.0.1
              advertisedPort: 32005
            - broker: 1
              nodePort: 32006
              advertisedHost: 127.0.0.1
              advertisedPort: 32006
            - broker: 2
              nodePort: 32007
              advertisedHost: 127.0.0.1
              advertisedPort: 32007
    authorization:
      type: simple
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
  entityOperator:
    topicOperator: {}
    userOperator: {}
